version: 2.1
orbs:
  architect: giantswarm/architect@5.12.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: Package and push aws-nth-bundle chart
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: aws-nth-bundle
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
