# --- BUNDLE-ONLY ----------------------------------------------------------------
ociRepositoryUrl: oci://gsoci.azurecr.io/charts/giantswarm/aws-node-termination-handler
# clusterID: ""

# --- UPSTREAM -------------------------------------------------------------------
image:
  registry: gsoci.azurecr.io
  name: giantswarm/aws-node-termination-handler
  tag: "v1.25.2"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name:
  annotations: {}

enableSqsTerminationDraining: true

replicas: 2

podDisruptionBudget:
  maxUnavailable: 1

serviceMonitor:
  create: true
  interval: 60s
  sampleLimit: 5000

enablePrometheusServer: true
prometheusServerPort: 9092

checkTagBeforeDraining: false

useHostNetwork: false

resources:
  requests:
    cpu: 0.1
    memory: 100Mi
  limits:
    cpu: 0.1
    memory: 100Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - aws-node-termination-handler
        topologyKey: kubernetes.io/hostname
      weight: 1

podSecurityContext:
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL

# --- EXTRAS ---------------------------------------------------------------------
verticalPodAutoscaler:
  enabled: true
  maxAllowed:
    cpu: 200m
    memory: 200Mi
  minAllowed:
    cpu: 50m
    memory: 50Mi

networkPolicy:
  enabled: true

global:
  podSecurityStandards:
    enforced: true
