# --- UPSTREAM -------------------------------------------------------------------
upstream:
  nameOverride: aws-node-termination-handler

# --- EXTRAS ---------------------------------------------------------------------
preflightCheck:
  enabled: true
  deploymentName: aws-pod-identity-webhook-app
  image:
    registry: gsoci.azurecr.io
    name: giantswarm/kubectl
    tag: 1.31.4

networkPolicy:
  enabled: true

verticalPodAutoscaler:
  enabled: true
  maxAllowed:
    cpu: 200m
    memory: 200Mi
  minAllowed:
    cpu: 50m
    memory: 50Mi

global:
  podSecurityStandards:
    enforced: true
