apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    app-operator.giantswarm.io/depends-on: {{ $.Values.clusterID }}-prometheus-operator-crd
  name: {{ $.Values.clusterID }}-aws-node-termination-handler
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: aws-node-termination-handler
  namespace: kube-system
  # used by renovate
  # repo: giantswarm/aws-node-termination-handler-app
  version: 1.21.0
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
{{- if or ($.Values.proxy).httpProxy ($.Values.proxy).httpsProxy ($.Values.proxy).noProxy }}
  - kind: secret
    name: {{ $.Values.clusterID }}-node-termination-handler-proxy
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- if (($.Values.awsNodeTerminationHandler).values) }}
  - kind: configMap
    name: {{ $.Values.clusterID }}-node-termination-handler-config
    namespace: {{ $.Release.Namespace }}
{{- end }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-aws-nth-crossplane-resources
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true
  name: aws-nth-crossplane-resources
  namespace: {{ $.Release.Namespace }}
  # used by renovate
  # repo: giantswarm/aws-nth-crossplane-resources
  version: 1.1.1
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
