apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-aws-node-termination-handler
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-test
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade: 
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: aws-node-termination-handler
  namespace: kube-system
  version: 1.19.0-7a77c1418fd1421d4cdf5dcb440b58ee3be74729
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
{{- if (($.Values.awsNodeTerminationHandler).values) }}
  - kind: configMap
    name: {{ $.Values.clusterID }}-node-termination-handler-config
    namespace: {{ $.Release.Namespace }}
{{- end }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-nth-crossplane-resources
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-test
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true
  name: nth-crossplane-resources
  namespace: {{ $.Release.Namespace }}
  version: 0.0.0-3171ffa26b7596cc88cdbcd3533665ba7e30abea
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
