---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: {{ $.Values.clusterID }}-aws-node-termination-handler
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aws-nth-bundle.labels" $ | nindent 4 }}
spec:
  url: {{ .Values.ociRepositoryUrl }}
  ref:
    tag: {{ .Chart.Version }}
  interval: 24h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $.Values.clusterID }}-aws-node-termination-handler
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aws-nth-bundle.labels" $ | nindent 4 }}
spec:
  releaseName: aws-node-termination-handler
  targetNamespace: kube-system
  storageNamespace: kube-system
  dependsOn:
  - name: {{ $.Values.clusterID }}-prometheus-operator-crd
  chartRef:
    kind: OCIRepository
    name: {{ $.Values.clusterID }}-aws-node-termination-handler
  kubeConfig:
    secretRef:
      name: {{ $.Values.clusterID }}-kubeconfig
  # dependsOn:
    # TODO: enable once https://github.com/giantswarm/cluster-aws/pull/1758/changes is merged
    # also remove pre-flight hook from the sub-chart
    # - name: {{ $.Values.clusterID }}-aws-pod-identity-webhook
    # - name: {{ $.Values.clusterID }}-kyverno-crds
  interval: 1m
  timeout: 15m
  install:
    remediation:
      retries: -1
      remediateLastFailure: false
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  values:
    upstream:
      enableSqsTerminationDraining: true
      queueURL: {{ include "aws-nth-bundle.queueURL" $ | trim | quote }}
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: {{ include "aws-nth-bundle.nodeRoleArn" $ | quote }}
  valuesFrom:
{{- if or ($.Values.proxy).httpProxy ($.Values.proxy).httpsProxy ($.Values.proxy).noProxy }}
  - kind: Secret
    name: {{ $.Values.clusterID }}-node-termination-handler-proxy
    valuesKey: values
    optional: false
{{- end }}
{{- if (($.Values.awsNodeTerminationHandler).values) }}
  - kind: ConfigMap
    name: {{ $.Values.clusterID }}-node-termination-handler-config
    valuesKey: values
    optional: false
{{- end }}
