{{- $clusterID := include "aws-nth-bundle.clusterID" . -}}
{{- $cmvalues := (include "aws-nth-bundle.crossplaneConfigData" .) | fromYaml -}}
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{ $clusterID }}-nth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-nth-bundle.labels" . | nindent 4 }}
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {{ include "aws-nth-bundle.trustPolicyStatements" . | nindent 10 }}
        ]
      }
    tags:
      "giantswarm.io/cluster": {{ $clusterID }}
      "sigs.k8s.io/cluster-api-provider-aws/cluster/{{ $clusterID }}": owned
  providerConfigRef:
    name: {{ $clusterID }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ $clusterID }}-nth-sqs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-nth-bundle.labels" . | nindent 4 }}
spec:
  forProvider:
    policyArn: arn:{{ $cmvalues.awsPartition }}:iam::aws:policy/AmazonSQSReadOnlyAccess
    roleRef:
      name: {{ $clusterID }}-nth
  providerConfigRef:
    name: {{ $clusterID }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ $clusterID }}-nth-asg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-nth-bundle.labels" . | nindent 4 }}
spec:
  forProvider:
    policyArn: arn:{{ $cmvalues.awsPartition }}:iam::aws:policy/AutoScalingReadOnlyAccess
    roleRef:
      name: {{ $clusterID }}-nth
  providerConfigRef:
    name: {{ $clusterID }}
